-- 創建模式
CREATE SCHEMA IF NOT EXISTS SPL_PRODUCT;
use SPL_PRODUCT;

DROP TABLE IF EXISTS SPL_PRODUCT.PRODUCT;
CREATE TABLE PRODUCT (
    product_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    product_name NVARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    description TEXT NOT NULL,
    category VARCHAR(50) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS SPL_PRODUCT.PRODUCT_DETAIL;
CREATE TABLE PRODUCT_DETAIL (
    product_detail_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    product_id BIGINT NOT NULL,
    specification NVARCHAR(100),
    additional_categories NVARCHAR(100),
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
);

DROP TABLE IF EXISTS SPL_PRODUCT.PRODUCT_IMAGE;
CREATE TABLE PRODUCT_IMAGE (
    product_image_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    product_id BIGINT NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    image_type VARCHAR(50) COMMENT 'MAIN: 主圖, ADDITIONAL: 附圖',
    image_sort INT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS SPL_PRODUCT.CART;
CREATE TABLE CART (
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INT NOT NULL
);

CREATE TABLE PRODUCT_COMMENT (
    product_comment_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    product_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    comment_rank INT NOT NULL,
    comment_detail TEXT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);