CREATE SCHEMA IF NOT EXISTS `SPL_MEMBER` DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;
DROP TABLE IF EXISTS SPL_MEMBER.USER;
USE SPL_MEMBER;
CREATE TABLE USER (
    USER_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD CHAR(255) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    PHONE_NUMBER CHAR(20) UNIQUE,
    DATE_OF_BIRTH TIMESTAMP,
    GENDER TINYINT(1) NOT NULL COMMENT 'male: 1, female: 2',
    LAST_LOGIN_DATE TIMESTAMP,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
DROP TABLE IF EXISTS SPL_MEMBER.ROLE;
CREATE TABLE ROLE (
    ROLE_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ROLE_TYPE CHAR(20) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR(100),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
DROP TABLE IF EXISTS SPL_MEMBER.USER_ROLE;
CREATE TABLE USER_ROLE (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;