USE ORDER_MODULE;

-- 禁用外鍵檢查，以避免因外鍵約束而無法刪除表格
SET FOREIGN_KEY_CHECKS = 0;

-- 刪除所有表格
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS ORDERS_DETAIL;
DROP TABLE IF EXISTS ORDER_EVAL;
DROP TABLE IF EXISTS SALER;
DROP TABLE IF EXISTS RETURN_RECORD;

-- 重新啟用外鍵檢查
SET FOREIGN_KEY_CHECKS = 1;

-- 確認所有表格已被刪除
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'ORDER_MODULE';